---
- hosts: webservers
  become: yes
  become_user: root
  tasks:
    - name: yum install opstools
      yum: pkg={{ item }} state=installed
      with_items:
        - epel-release
        - telnet
        - wget
        - rsync
        - tree
        - tcpdump
        - sysstat
        - dstat
        - vim-enhanced
        - git
        - htop
