############################################################
# hands-on3: handlers
############################################################

# tasks/swap.yml
- name: make swap
  shell: mkswap {{ swapfile_path }}
  when: result|failed

- name: swapon
  shell: swapon {{ swapfile_path }}

- name: mount swap
  mount: name=swap src={{ swapfile_path }} fstype=swap state=present

- name: restart nginx
  service: name=nginx state=restarted

