############################################################
# webserver: install
############################################################

- name: yum install opstools epel-release
  yum: pkg=epel-release state=installed

- name: default unabled repository
  replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - epel.repo
  ignore_errors: True

- name: install opstools
  yum: pkg={{item}} enablerepo=epel state=installed
  ignore_errors: True
  with_items:
    - htop
    - glances
    - ack
    - the_silver_searcher
