############################################################
# webserver: swap
############################################################

- name: check swapfile
  command: test -e {{ swapfile_path }}
  register: result
  always_run: yes
  ignore_errors: yes
  changed_when: no

- name: create swapfile
  command: fallocate -l 512m {{ swapfile_path }}
  when: result|failed
  notify:
    - make swap
    - swapon
    - mount swap
