############################################################
# webserver: swap
############################################################

- name: check swapfile
  stat: path={{swapfile_path}}
  register: result

- name: create swapfile
  shell: dd if=/dev/zero of={{ swapfile_path }} bs=1M count=1024
  when: not result.stat.exists
  notify:
    - make swap
    - swapon
    - mount swap

- name: set permission "0600 root:root" swapfile
  file: path={{ swapfile_path }} state=file owner=root group=root mode=0600
  ignore_errors: yes
