############################################################
# __creates__
############################################################

ag_url: http://swiftsignal.com/packages/centos/6/x86_64/the-silver-searcher-0.14-1.el6.x86_64.rpm
swapfile_path: /mnt/swap.img
